import Head from 'next/head'
import { Inter } from '@next/font/google'
import Footer from '@/components/Footer'
import Counter from '@/components/Counter'
import TestBlog from '@/components/TestBlog'

const inter = Inter({ subsets: ['latin'] })

export default function Course() {
  return (
    <>
      <Head>
        <title>Courses | Shifu FX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
      <TestBlog />
      <Counter />
      <Footer />
    </>
  )
}

