import Head from 'next/head'
import { Inter } from '@next/font/google'
import Hero from '@/components/Hero'
import Footer from '@/components/Footer'
import { Integrate } from '@/components/Integrate'
import Contact from '@/components/Contacts'
import Testimonials from '@/components/Testimonials'

const inter = Inter({ subsets: ['latin'] })

function Home() {
  return (
    <>
      <Head>
        <title>Home | Shifu FX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
        <Hero />
        <Integrate />
        <Contact />
        <Testimonials />
        <Footer />
    </>
  )
}

export default Home
